#!/system/bin/sh
# Copyright (c) 2017, Stripalov. All rights reserved.
# Disable NuPlayer
setprop persist.sys.media.use-awesome true
# Enable 2D accelerate
setprop persist.sys.ui.hw 1
# Fix device name
setprop persist.sys.device_name alto5_premium