#!/system/bin/sh
# Copyright (c) 2017, Stripalov. All rights reserved.
# Copyright (c) 2015-2016, FocalTech, TCT. All rights reserved.
# Version: 1.5
# Start gesture_listener
su -c /system/bin/gesture_listener